### PR TITLE
Inconsistent number of hints between games

### PR DESCRIPTION
**Pull request by CaitSith2**
Fixed a bug that caused the number of hints from one game to the next be inconsistent.

### CODE REVIEW

**Comment by Jarno458** [comment]
can you be a bit more clear about the issue here and how this change fixes it?

**Comment by CaitSith2** [comment]
The best I can do is count the number of hints that are actually exposed when you start a new game, and do that several times.   Even on hard,  you may not get 20 hints exposed every single time.

What this change does, is checks to see if the randomly chosen set has already been revealed, and if so,  pick a new random pair, so that you are guaranteed to expose the exact number of hints that are coded in.

Also, on a related note,  even with 57 revealed exactly, I still managed to end up with a puzzle that had two solutions, of which, only one of them was registered as correct, even though both were technically correct according to the sudoku rules.

**Comment by CaitSith2** [comment]
The real solution would actually be to start with all revealed,  remove a random one, check that there is still only one unique solution,  and repeat till it reaches the minimum number revealed or it can't hide any more, whichever happens first, for the chosen difficulty level.

**Comment by Jarno458** [comment]
Thank you for your efforts, i am pretty sure this got resolved when we started switching backend libraries

**Pull request closed without merging**
